# DiscordMC by manuelgu
# https://www.spigotmc.org/resources/17067/
settings:
  token: 'TOKEN_HERE'
  send_game_login: true
  send_game_logout: true
  send_game_chat: true
  send_game_chat_also_to_console: true
  send_discord_chat: true
  send_death_message: true
  use_nicknames: false
  use_mentions: true
  use_ingame_format: false
  check_for_updates: true
  admin_chat_prefix: "Â§cAdminChat>"
  templates:
    chat_message_discord: '**%user**: %message'
    player_join_minecraft: '%user joined the game'
    player_leave_minecraft: '%user left the game'
    chat_message_minecraft: '&b(discord [%channel]) &r%user >> %message'
  channels:
    minecraft_to_discord:
      - 'chatlog'
      - 'chatting'
    discord_to_minecraft:
      - 'chatting'
      - 'announcement'
  discord_commands:
    enabled: true
    command_prefix: '?'
